### PR TITLE
use native secp256k1

### PR DESCRIPTION
**Pull request by q9f**
ref #4 

just seeing how my library applies in the wild.

### CODE REVIEW

**Comment by kingsleyh** [comment]
This looks pretty good. Your secp256k1 library looks good. Maybe I can convince you to help out on my blockchain platform https://sushichain.io :)

**Comment by q9f** [comment]
replaced all secp256k1 with the native library except for encrypt/decrypt. ref https://github.com/q9f/secp256k1.cr/issues/22

note, that apparently, I used a different signing algorithm. this should not be merged until I figure out how to match your signature scheme. tests pass because it only verifies self-generated signatures.

**Comment by kingsleyh** [comment]
I'm going to start using this - the signing algorithm is not an issue - I've re-worked a few things so it's compatible.

**Comment by q9f** [comment]
cool

**Pull request merged**
